# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-09 07:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a_title', models.CharField(max_length=50)),
                ('a_content', models.TextField()),
                ('a_time', models.TimeField()),
                ('a_is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_text', models.TextField()),
                ('c_image', models.CharField(max_length=500)),
                ('c_time', models.TimeField()),
                ('c_is_active', models.BooleanField(default=True)),
                ('a_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.Article')),
            ],
        ),
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to_uid', models.IntegerField()),
                ('r_text', models.TextField()),
                ('r_image', models.CharField(max_length=500)),
                ('r_time', models.TimeField()),
                ('r_is_active', models.BooleanField(default=True)),
                ('r_type', models.CharField(max_length=30)),
                ('r_type_id', models.IntegerField()),
                ('c_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.Comment')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('u_name', models.CharField(max_length=30)),
                ('u_pwd', models.CharField(max_length=30)),
                ('u_email', models.EmailField(max_length=254, null=True)),
                ('u_phone', models.CharField(max_length=20)),
                ('u_portrait', models.CharField(max_length=500)),
                ('u_profile', models.TextField()),
                ('u_is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='reply',
            name='from_uid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.User'),
        ),
        migrations.AddField(
            model_name='comment',
            name='from_uid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.User'),
        ),
        migrations.AddField(
            model_name='article',
            name='u_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.User'),
        ),
    ]
