# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-09 07:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_user_u_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='a_time',
            field=models.DateTimeField(),
        ),
    ]
