# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-09 07:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_auto_20180909_1530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='c_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='reply',
            name='r_time',
            field=models.DateTimeField(),
        ),
    ]
