# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-10 04:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0005_article_a_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='a_time',
            field=models.DateTimeField(null=True),
        ),
    ]
