# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-10 07:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0006_auto_20180910_1200'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t_time', models.DateTimeField()),
            ],
        ),
    ]
