# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-11 03:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0011_auto_20180911_1105'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='t_time',
        ),
    ]
