# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-13 14:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0013_auto_20180913_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='u_portrait',
            field=models.CharField(default='https://ss0.bdstatic.com/94oJfD_bAAcT8t7mm9GUKT-xh_/timg?image&quality=100&size=b4000_4000&sec=1536847595&di=8153cabe0874f534fd65f61e19183e9b&src=http://b-ssl.duitang.com/uploads/item/201607/24/20160724094822_UST4m.jpeg', max_length=500),
        ),
    ]
