# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-14 12:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0016_auto_20180914_1724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reply',
            name='r_type',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='u_profile',
            field=models.TextField(default='用户没有填写任何个人信息...'),
        ),
    ]
