# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-15 01:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0017_auto_20180914_2053'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='a_comment_count',
            field=models.IntegerField(default=0, max_length=6),
        ),
        migrations.AddField(
            model_name='article',
            name='a_read_count',
            field=models.IntegerField(default=0, max_length=10),
        ),
        migrations.AddField(
            model_name='user',
            name='u_address',
            field=models.CharField(max_length=50, null=True, verbose_name='地址'),
        ),
        migrations.AddField(
            model_name='user',
            name='u_time',
            field=models.CharField(max_length=30, null=True, verbose_name='注册时间'),
        ),
    ]
